# this is the name that we are going to call the plugin
name: Packet Test
# now we need to define the main class so it can load it.
main: Com.source.java.test.Main
# version number
version: 0.1
# plugin description
description: Blank Plugin
#commands below along with any descriptions or permissions you want to define.
commands:
  test:
    description: TEST